FROM openjdk:11-slim

ENV PRESTO_VERSION=${PRESTO_VERSION:-340}

# copy certs if has any
COPY conf/certificates/* /usr/local/share/ca-certificates/
RUN apt-get update && apt-get install -y ca-certificates curl bash && rm -rf /var/lib/apt/lists/*
RUN update-ca-certificates 2>/dev/null || true && echo "NOTE: CA warnings suppressed."
RUN curl https://repo1.maven.org/maven2/io/prestosql/presto-cli/$PRESTO_VERSION/presto-cli-$PRESTO_VERSION-executable.jar -o ./presto
RUN chmod +x ./presto
