- name: Terraform presto {{ mode }}
  terraform:
    project_path: ../../example/presto_{{ mode }}
    force_init: true
    state: present
  register: terraform

- name: Terraform presto {{ mode }} stdout
  debug:
    msg: "{{terraform.stdout}}"
