- name: Terraform trino {{ mode }}
  terraform:
    project_path: ../../example/trino_{{ mode }}
    force_init: true
    state: present
  register: terraform

- name: Terraform trino {{ mode }} stdout
  debug:
    msg: "{{terraform.stdout}}"
